/*  	cncsman.h v01.01

	Функции ручного режима

	Подпроект: CNCSHOW
	Проект:    ELMIS CNC.

	Copyright (c) ELMIS, 1993
	Все права защищены.
*/

void Mn0(WORD *modes);
void Mn1(CHAR cod,WORD *modes); /*режим толчок */
void Otl(CHAR cod,WORD *modes); /* отладка */
void Mn3(CHAR cod,WORD *modes);
void Mn31(WORD *modes);
void Mn32(WORD *modes);
void Mn33(WORD *modes);
void Mn34(WORD *modes);
void Mn35(WORD *modes);

     
