/*  	cncsedit.h v01.01

	Функции редима редактор

	Подпроект: CNCSHOW
	Проект:    ELMIS CNC.

	Copyright (c) ELMIS, 1993
	Все права защищены.
*/

/* Функции режима Редактор */
void Ep0(CHAR cod,WORD *modes);
void Ep1(CHAR cod,WORD *modes);
void Ep2(CHAR cod,WORD *modes);
void Ep3(CHAR cod,WORD *modes);
void Ep4(CHAR cod,WORD *modes);
void Ep5(CHAR cod,WORD *modes);
void Ep51(CHAR cod,WORD *modes);
void Ep52(CHAR cod,WORD *modes);
void Ep53(CHAR cod,WORD *modes);
void Ep54(CHAR cod,WORD *modes);
void Ep55(CHAR cod,WORD *modes);
void Ep551(CHAR cod,WORD *modes);
void Ep553(CHAR cod,WORD *modes);
void Ep554(CHAR cod,WORD *modes);
void Ep5531(CHAR cod,WORD *modes);
void Ep5532(CHAR cod,WORD *modes);
void Ep5533(CHAR cod,WORD *modes);
void Ep5534(CHAR cod,WORD *modes);
void Ep5545(CHAR cod,WORD *modes);
                                                                                                                                                                                                                                                               
     
