/*  	cncsdiag.h v01.01

	Функции режима диагностика

	Подпроект: CNCSHOW
	Проект:    ELMIS CNC.

	Copyright (c) ELMIS, 1993
	Все права защищены.
*/

/* Функции режима Диагностика */
void Dg0(CHAR cod,WORD *modes);
void Dg1(CHAR cod,WORD *modes);
void Dg13(CHAR cod,WORD *modes);
void Dg15(void);
void Dg2(CHAR cod,WORD *modes);
void Dg3(CHAR cod,WORD *modes);
void Dg35(void);
void Dg21(CHAR cod,WORD *modes);
void Dg23(CHAR cod,WORD *modes);
void Dg232(CHAR cod,WORD *modes);
void Dg2322(CHAR cod,WORD *modes);
void Dg233(CHAR cod,WORD *modes);
void Dg2332(CHAR cod,WORD *modes);
void Dg25(CHAR cod,WORD *modes);
void Dg253(CHAR cod,WORD *modes);
void Dg2532(CHAR cod,WORD *modes);

     
