/*  	cncskor.h v01.01

	Функции режима коррекции

	Подпроект: CNCSHOW
	Проект:    ELMIS CNC.

	Copyright (c) ELMIS, 1993
	Все права защищены.
*/

void Ek0(CHAR cod,WORD *modes);
void Ek1(CHAR cod,WORD *modes);
void Ek2(CHAR cod,WORD *modes);
void Ek3(CHAR cod,WORD *modes);
void Ek4(CHAR cod,WORD *modes);
void Ek5(CHAR cod,WORD *modes);
void Ek11(CHAR cod,WORD *modes);
void Ek12(CHAR cod,WORD *modes);
void Ek13(CHAR cod,WORD *modes);
void Ek14(CHAR cod,WORD *modes);
void Ek15(CHAR cod,WORD *modes);
void Ek151(CHAR cod,WORD *modes);
void Ek152(CHAR cod,WORD *modes);
void Ek153(CHAR cod,WORD *modes);
void Ek154(CHAR cod,WORD *modes);
void Ek155(CHAR cod,WORD *modes);
void Ek1551(CHAR cod,WORD *modes);
void Ek1553(CHAR cod,WORD *modes);
void Ek1554(CHAR cod,WORD *modes);
void Ek1555(CHAR cod,WORD *modes);
void Ek21(CHAR cod,WORD *modes);
void Ek22(CHAR cod,WORD *modes);
void Ek23(CHAR cod,WORD *modes);
void Ek24(CHAR cod,WORD *modes);
void Ek25(CHAR cod,WORD *modes);
void Ek251(CHAR cod,WORD *modes);
void Ek252(CHAR cod,WORD *modes);
void Ek253(CHAR cod,WORD *modes);
void Ek254(CHAR cod,WORD *modes);
void Ek255(CHAR cod,WORD *modes);
void Ek2551(CHAR cod,WORD *modes);
void Ek2553(CHAR cod,WORD *modes);
void Ek2554(CHAR cod,WORD *modes);
void Ek2555(CHAR cod,WORD *modes);
void Ek31(CHAR cod,WORD *modes);
void Ek32(CHAR cod,WORD *modes);
void Ek33(CHAR cod,WORD *modes);
void Ek34(CHAR cod,WORD *modes);
void Ek35(CHAR cod,WORD *modes);
void Ek351(CHAR cod,WORD *modes);
void Ek352(CHAR cod,WORD *modes);
void Ek353(CHAR cod,WORD *modes);
void Ek354(CHAR cod,WORD *modes);
void Ek355(CHAR cod,WORD *modes);
void Ek3551(CHAR cod,WORD *modes);
void Ek3553(CHAR cod,WORD *modes);
void Ek3554(CHAR cod,WORD *modes);
void Ek3555(CHAR cod,WORD *modes);
void Ek41(CHAR cod,WORD *modes);
void Ek42(CHAR cod,WORD *modes);
void Ek43(CHAR cod,WORD *modes);
void Ek44(CHAR cod,WORD *modes);
void Ek45(CHAR cod,WORD *modes);
void Ek451(CHAR cod,WORD *modes);
void Ek452(CHAR cod,WORD *modes);
void Ek453(CHAR cod,WORD *modes);
void Ek454(CHAR cod,WORD *modes);
void Ek455(CHAR cod,WORD *modes);
void Ek4551(CHAR cod,WORD *modes);
void Ek4553(CHAR cod,WORD *modes);
void Ek4554(CHAR cod,WORD *modes);
void Ek4555(CHAR cod,WORD *modes);
void Ek51(CHAR cod,WORD *modes);
void Ek52(CHAR cod,WORD *modes);
void Ek53(CHAR cod,WORD *modes);
void Ek54(CHAR cod,WORD *modes);
void Ek55(CHAR cod,WORD *modes);
void Ek551(CHAR cod,WORD *modes);
void Ek552(CHAR cod,WORD *modes);
void Ek553(CHAR cod,WORD *modes);
void Ek554(CHAR cod,WORD *modes);
void Ek555(CHAR cod,WORD *modes);
void Ek5551(CHAR cod,WORD *modes);
void Ek5553(CHAR cod,WORD *modes);
void Ek5554(CHAR cod,WORD *modes);
void Ek5555(CHAR cod,WORD *modes);

     
