/*  	cncsauto.h v01.01

	Функции режима автомат

	Подпроект: CNCSHOW
	Проект:    ELMIS CNC.

	Copyright (c) ELMIS, 1993
	Все права защищены.
*/

			/* Функции режима автомат */
void At0(WORD *modes);			       
void At1(CHAR cod,WORD *modes);
void At2(CHAR cod,WORD *modes);
void At3(CHAR cod,WORD *modes);
void At31(CHAR cod,WORD *modes);
void At32(CHAR cod,WORD *modes);
void At34(CHAR cod,WORD *modes);
void At35(CHAR cod,WORD *modes);
void At354(WORD *modes);
void At355(WORD *modes);

     
