/*
   cncvcomd.h

   Ввод команд опеpатоpа

   Copyright (c) ELMIS ltd 1993.

*/

#ifndef __CNCVCOMD_H
#define __CNCVCOMD_H

class ComandDialog : public TWindow
{

 public:

//  void drawStatic();
//  virtual void draw();
/*
  ComandDialog( ) : TWindow( bounds, "Команды упpавления", 3),
		   TWindowInit( &ComandDialog::initFrame )
  {
   palette = wpCyanWindow;
   options |= ofSelectable | ofFramed | ofPreProcess | ofTopSelect;
  } */
};


#endif


