’ … Š “ ™ ˆ …
 ’…Š“™ˆ…
 ŠŽ…—›…
 Ž‹œ „…’€‹ˆ
 Ž’‚Ž„
 Ž‘’€’ŽŠ
€‘‘Žƒ‹€‘Ž‚€ˆ…
 €‘Ž‹ž’›…   ‚›Š‹. ˆ‘•. ‹Š.
         ŽŽŽ’› 
       ‡€„€›… F ¨ S
       €Š’ˆ‚›… Ž‘ˆ
ŠŽ…– Š€’€‹Žƒ€
‹ŽŠˆŽ‚Š€, …Ž•Ž„ˆŒ ‘’Ž Žƒ€ŒŒ›
… ‚›€€ Žƒ€ŒŒ€ Ž€Ž’Šˆ
ˆŒŸ          €‡Œ…  „€’€
‚…ŒŸ       ‡€™ˆ’€
’…•Ž‹Žƒˆ—…‘Šˆ… Žƒ€ŒŒ›
’€‹ˆ–› ‘Œ…™…ˆŸ “‹…‰
’€‹ˆ–› ŠŽ…Š–ˆ‰ ˆ‘’“Œ…’€
Žƒ€Œˆ“…Œ›… €€Œ…’›
‘’€Ž—›… €€Œ…’›
’€‹ˆ–› €‘Ž‹Ž†…ˆŸ ˆ‘’“Œ…’€
€Ž‹œ?
‚› “‚……›?
 ‚ˆŒ€ˆ…, Ž˜ˆŠ€ ! 
’€ŠŽ‰ ”€‰‹ “†… …‘’œ!
”€‰‹ ‡€™ˆ™…!
€€Œ…’› ‘’€Š€ ‡€™ˆ™…›!
>
Ž‚Ž… ˆŒŸ? >
Ž‚Ž… ˆŒŸ >
ˆŒŸ Žƒ€ŒŒ› >
ˆŒŸ Ž„Žƒ€ŒŒ› >
ŠŽ‹ˆ—…‘’‚Ž Ž“‘ŠŽ‚ Ž„Žƒ€ŒŒ› >
ŽŒ… Š€„€ >
‘ŠŽˆŽ‚€Ž %6u €‰’ 
…„€Š’ˆ“…’‘Ÿ ’€‹ˆ–€
Ž˜ˆŠ€ €Ž€!
ŽŒ… DRC->CNC
ŽŒ… CNC->DRC
Ž˜ˆŠ€ Ž’Š›’ˆŸ ”€‰‹€ %s
ˆŒŸ
SA
ˆ’
‚•Ž„›… ‘ˆƒ€‹› L‘ -> NC
SE
‚›•Ž„›… ‘ˆƒ€‹› N‘ -> PLC
‘‚ŽŽ„Ž‰ Ž…€’ˆŽ‰ €ŒŸ’ˆ - %lu K €‰’.
Ž˜ˆŠ€ —’…ˆŸ ”€‰‹€ %s
Ž˜ˆŠ€ “€‚‹Ÿž™…‰ Žƒ€ŒŒ›
Žƒ€ˆ—…ˆ… „Ž“‘’ˆŒŽ‰ ‡Ž›
Œ€’…Œ€’ˆ—…‘ŠŽ… Žƒ€ˆ—…ˆ… ‚ " + "
Œ€’…Œ€’ˆ—…‘ŠŽ… Žƒ€ˆ—…ˆ… ‚ " - "
‹ŽŠˆŽ‚Š€ „‚ˆ†…ˆŸ


