 1400
 1 ось в позиции                           
 2 ось в позиции                           
 3 ось в позиции                           
 4 ось в позиции                           
 5 ось в позиции                           
 6 ось в позиции                           
 7 ось в позиции                                
 8 ось в позиции                           
 Подтверждение выезда в ноль 1 ось         
 Подтверждение выезда в ноль 2 ось         
 Подтверждение выезда в ноль 3 ось         
 Подтверждение выезда в ноль 4 ось         
 Подтверждение выезда в ноль 5 ось         
 Подтверждение выезда в ноль 6 ось         
 Подтверждение выезда в ноль 7 ось         
 Подтверждение выезда в ноль 8 ось         
 N = зад. = N факт. S1                     
 N = 0              S1                     
 Шпиндель 1 соориентирован                 
					   
					   
					   
					   
					   
 N = зад. = N факт. S2                     
 N = 0              S2                     
 Шпиндель 2 соориентирован                 
					   
					   
					   
					   
					   
 Команда перемещения 1 оси в +            
 Команда перемещения 1 оси в -            
 Команда перемещения 2 оси в +            
 Команда перемещения 2 оси в -            
 Команда перемещения 3 оси в +            
 Команда перемещения 3 оси в -            
 Команда перемещения 4 оси в +            
 Команда перемещения 4 оси в -            
 Команда перемещения 5 оси в +            
 Команда перемещения 5 оси в -            
 Команда перемещения 6 оси в +            
 Команда перемещения 6 оси в -            
 Команда перемещения 7 оси в +            
 Команда перемещения 7 оси в -            
 Команда перемещения 8 оси в +            
 Команда перемещения 8 оси в -            
 Готовность УЧПУ                          
 Активна G33                              
 Блокировка обмена                        
 Режим Автомат                            
 Покадровый                               
 Преднабор                                
 Толчок                                   
 Выезд в ноль                             
 Подтверждение приема координатной оси    
 Подтверждение выезда в ноль всех осей    
 Ускоренный ход                           
 Программа выполняется                    
 Тест без движения                        
 Общий сброс " RESET"                     
 Пропуск кадра                            
 Останов по М01                           
 Задание кадра                            
 Блокировка выдачи MST-функций            
 Возврат на контур                        
 Подача 0%                                
 Активна  G63 (подача 100%)               
 Активна  G84                             
 Активна  G86                             
 Разрешение сброса остатка пути           
 Строб М1                                 
 Строб М2                                 
 Строб М3                                 
 Строб Т1                                 
 Признак функции Т1                       
 Строб Т2                                 
 Признак функции Т2                       
					  
 Строб S1                                 
 Строб S2                                 
					  
					  
					  
					  
					  
					  
					  
					  
					  
					  
					  
					  
					  
					  
 Значение                                 
					  
 вспомогательной                         					  │
 функции             
					  
 М1        
					  
 Значение                                 
					  
 вспомогательной                 
					  
 функции             
					  
 М1        
					  
 Значение                                 
					  
 вспомогательной                 
					  
 функции             
					  
 М2        
					  
 Значение                                 
					  
 вспомогательной                 
					  
 функции             
					  
 М2        
					  
 Значение                                 
					  
 вспомогательной                 
					  
 функции             
					  
 М3        
					  
 Значение                                 
					  
 вспомогательной                 
					  
 функции             
					  
 М3        
					  
					  
 
					  
 Т1 слово                        
					  
					  
					  
					  
					  
					  
					  
 Т1 слово                        
					  
					  
					  
					  
					  
					  
					  
 Т2 слово                        
					  
					  
					  
					  
					  
					  
					  
 Т2 слово                        
					  
					  
					  
					  
					  
					  
					  
 S1 слово                        







 S1 слово                        







 S1 слово                        







 S1 слово                        







 S2 слово                        







 S2 слово                        







 S2 слово                        







 S2 слово                        




 Код кнопки принят                           
 Код аварийной кнопки принят                 





 Условие выполнения мгновенного снимка
 Подтверждение выполнения перемещения с интерф.
 Выполнение перемещения с интерфейса           
 Запрс на выполнение мгновенного снимка
 Строб обновления индикации│
 Признак адреса: 0-бит, 1-слово                
 Тип переменной:                               
 Е-1, А-2, М-3,                  
 D-4, T-5, Z-6.    



 Адрес переменной для индикации       







 Адрес переменной для индикации       







 Диапазон конечных выключателей        







 Диапазон конечных выключателей        







 DNC-сигналы                      







 DNC-сигналы                     
















 Контрольная сумма                 












