 1500
 Привод оси 1 включен
 Привод оси 2 включен
 Привод оси 3 включен
 Привод оси 4 включен
 Привод оси 5 включен
 Привод оси 6 включен
 Привод оси 7 включен
 Привод оси 8 включен
 Разрешение подачи оси 1
 Разрешение подачи оси 2
 Разрешение подачи оси 3
 Разрешение подачи оси 4
 Разрешение подачи оси 5
 Разрешение подачи оси 6
 Разрешение подачи оси 7
 Разрешение подачи оси 8
 Опорная точка оси 1
 Опорная точка оси 2
 Опорная точка оси 3
 Опорная точка оси 4
 Опорная точка оси 5
 Опорная точка оси 6
 Опорная точка оси 7
 Опорная точка оси 8
 Направление выезда в ноль оси 1
 Направление выезда в ноль оси 2
 Направление выезда в ноль оси 3
 Направление выезда в ноль оси 4
 Направление выезда в ноль оси 5
 Направление выезда в ноль оси 6
 Направление выезда в ноль оси 7
 Направление выезда в ноль оси 8
 Снижение скорости по оси 1
 Снижение скорости по оси 2
 Снижение скорости по оси 3
 Снижение скорости по оси 4
 Снижение скорости по оси 5
 Снижение скорости по оси 6
 Снижение скорости по оси 7
 Снижение скорости по оси 8
 Блокировка быстрого стола







 Подтверждение 1 ступени для 1 шпинделя
 Подтверждение 2 ступени для 1 шпинделя
 Подтверждение 3 ступени для 1 шпинделя
 Подтверждение 4 ступени для 1 шпинделя
 Подтверждение 1 ступени для 2 шпинделя
 Подтверждение 2 ступени для 2 шпинделя
 Подтверждение 3 ступени для 2 шпинделя
 Подтверждение 4 ступени для 2 шпинделя
 Толчковое перемещение 1 оси в +
 Толчковое перемещение 1 оси в -
 Толчковое перемещение 2 оси в +
 Толчковое перемещение 2 оси в -
 Толчковое перемещение 3 оси в +
 Толчковое перемещение 3 оси в -
 Толчковое перемещение 4 оси в +   
 Толчковое перемещение 4 оси в -            
 Толчковое перемещение 5 оси в +            
 Толчковое перемещение 5 оси в -            
 Толчковое перемещение 6 оси в +            
 Толчковое перемещение 6 оси в -            
 Толчковое перемещение 7 оси в +            
 Толчковое перемещение 7 оси в -            
 Толчковое перемещение 8 оси в +            
 Толчковое перемещение 8 оси в -        
 Величина 
 скорости 
 и шаговых 
 перемещений
 Потенциомер подачи внешний/внутренний
 Выезд в ноль
 Потенциометр шпинделя 1 внешний/внутренний
 Потенциометр шпинделя 2 внешний/внутренний



 Значение внешнего потенциометра подач







 Значение внешнего потенциометра 1 шпинделя







 Значение внешнего потенциометра 1 шпинделя




 Обнуление осей
 Восстановление абсолютных координат
 Разрешение очистки остаточного пути

 Разрешение возврата на контур
 Разрешение блокировки контроля изм. сист.
 Разрешение блокировки мат.ограничений
 Пуск
 Стоп
 Аварийный стоп
 Общий сброс
 Разрешение ввода кадра
 Блокировка реактирования
 Пропуск кадра
 Подтверждение М01
 Местный/дистанционный режим
 Номер
 передви-
 гаемой
 оси
 Номер точки
 координаты которой
 заданы в 
 параметрах
 Строб Т1 для 1 магазина
 Строб Т2 для 1 магазина
 Строб Т3 для 1 магазина

 Номер 
 активной
 KS - таблицы 
 для 1 шпинделя
 Строб Т1 для 2 магазина
 Строб Т2 для 2 магазина
 Строб Т3 для 2 магазина

 Номер 
 активной
 KS - таблицы 
 для 2 шпинделя

 Выполнение перемещения с интерфейса
 ? Подтверждение приема вспомогат. ф-ции
 Автоматический рестарт
 G84 по кадрам 



 Постоянное число оборотов для 1 шпинделя
 Толчковая скорость для 1 шпинделя
 0 вольт на ЦАП для первого шпинделя
 100% обороты первого шпинделя
 Вращение первого шпинделя по часовой М03
 Вращение первого шпинделя прот.часовой М04
 Ориентация шпинделя 1
 Стоп S для первого шпинделя М05
 Постоянное число оборотов для 2 шпинделя
 Толчковая скорость для 2 шпинделя
 0 вольт на ЦАП для второго шпинделя
 100% обороты второго шпинделя
 Вращение второго шпинделя по часовой М03
 Вращение второго шпинделя прот.часовой М04
 Ориентация шпинделя 2
 Стоп S для шпинделя М05



  Код
  кнопки 



  Блокирование кнопок системного пульта
  Квитирование блокировки обмена














 Динамическая индикация памяти контроллера    







 Динамическая индикация памяти контроллера







 Номер группы ошибок







 Байт ошибок































































































 Контрольная сумма






















