00 Привод включен ось
01 Разрешение подачи по оси
02 Опорная точка оси
03 Направление выезда в ноль по оси
04 Снижение скорости по оси
05 Блокировка быстрого стопа
06 Подтверждение 1 ступени для 1 шпинделя
06 Подтверждение 2 ступени для 1 шпинделя
06 Подтверждение 3 ступени для 1 шпинделя
06 Подтверждение 4 ступени для 1 шпинделя
06 Подтверждение 1 ступени для 2 шпинделя
06 Подтверждение 2 ступени для 2 шпинделя
06 Подтверждение 3 ступени для 2 шпинделя
06 Подтверждение 4 ступени для 2 шпинделя
07 Толчковое перемещение 1 оси в +
07 Толчковое перемещение 1 оси в -
07 Толчковое перемещение 2 оси в +
07 Толчковое перемещение 2 оси в -
07 Толчковое перемещение 3 оси в +
07 Толчковое перемещение 3 оси в -
07 Толчковое перемещение 4 оси в +
07 Толчковое перемещение 4 оси в -
08 Толчковое перемещение 5 оси в +
08 Толчковое перемещение 5 оси в -
08 Толчковое перемещение 6 оси в +
08 Толчковое перемещение 6 оси в -
08 Толчковое перемещение 7 оси в +
08 Толчковое перемещение 7 оси в -
08 Толчковое перемещение 8 оси в +
08 Толчковое перемещение 8 оси в -
09 Величина
09 скорости и
09 шаговых
09 перемещений
09 Потенциометр подачи внешний/внутренний
09 Выезд в ноль
09 Потенциометр шпинделя 1 внешний/внутренний
09 Потенциометр шпинделя 2 внешний/внутренний
10 Значение
10 внешнего
10 потенциометра
10 подач
11 Значение
11 внешнего
11 потенциометра
11 1 шпинделя
12 Значение
12 внешнего
12 потенциометра
12 2 шпинделя
13 Обнуление осей
13 Восстановление абсолютных координат
13 Разрешение очистки остаточного пути
13
13 Разрешение возврата на контур
13 Разреш-е блок. контроля измер. сист-ы
13 Разреш-е блок. математ-х ограничений
13 Пуск
14 Стоп
14 Аварийный стоп
14 Общий сброс
14 Разрешение ввода кадра
14 Блокировка редактирования
14 Пропуск кадра
14 Подтверждение М01
14 Местный/дистанционный режим
15 Номер
15 передвигаемой
15
15 оси
15 Номер точки
15 координаты которой
15 заданы в параметрах
16 Строб Т1 для 1 магазина
16 Строб Т2 для 1 магазина
16 Строб Т3 для 1 магазина
16 Номер активной
16 KS-таблицы
16 для 1 шпинделя
17 Строб Т1 для 2 магазина
17 Строб Т2 для 2 магазина
17 Строб Т3 для 2 магазина
17 Номер активной
17 KS-таблицы
17 для 2 шпинделя
18
18 Выполнение перемещения с интерфейса
18 Подтверждение приема вспомог-й функ-и
18 Автоматический рестарт
18 G84 по кадрам
18
18
18
19 Постоянное число оборотов для 1 шпинделя
19 Толчковая скорость для 1 шпинделя
19 0 вольт на ЦАП для 1 шпинделя
19 100% обороты 1 шпинделя
19 Вращение 1 шпинделя по часовой М03
19 Вращение 1 шпинделя против часовой М04
19 Ориентация 1 шпинделя
19 Стоп S для 1 шпинделя М05
20 Постоянное число оборотов для 2 шпинделя
20 Толчковая скорость для 2 шпинделя
20 0 вольт на ЦАП для 2 шпинделя
20 100% обороты 2 шпинделя
20 Вращение 2 шпинделя по часовой М03
20 Вращение 2 шпинделя против часовой М04
20 Ориентация 2 шпинделя
20 Стоп S для 2 шпинделя М05
21 Код кнопки
22 Блокирование кнопок системного пульта
22 Квитирование блокировки обмена
22
22
22
22
22
22
23
24 Динамическая индикация памяти контроллера
25 Динамическая индикация памяти контроллера
26 Номер группы ошибок
27 Байт ошибок
28 Байт ошибок
29 Байт ошибок
30 Байт ошибок
31 Байт ошибок
32 Байт ошибок
33 Байт ошибок
34 Байт ошибок
35 Байт ошибок
36 Байт ошибок
37 Байт ошибок
38 Байт ошибок
39
40 Контрольная сумма

