00 В позиции ось
01 Подтверждение выезда в ноль по оси
02 Nзад.=Nфакт.   S1
02 N=0            S1
02 Шпиндель 1 сориентирован
02
02
02
02
02
03 Nзад.=Nфакт.   S2
03 N=0            S2
03 Шпиндель 2 сориентирован
03
03
03
03
03
04 Команда перемещения 1 оси в +
04 Команда перемещения 1 оси в -
04 Команда перемещения 2 оси в +
04 Команда перемещения 2 оси в -
04 Команда перемещения 3 оси в +
04 Команда перемещения 3 оси в -
04 Команда перемещения 4 оси в +
04 Команда перемещения 4 оси в -
05 Команда перемещения 5 оси в +
05 Команда перемещения 5 оси в -
05 Команда перемещения 6 оси в +
05 Команда перемещения 6 оси в -
05 Команда перемещения 7 оси в +
05 Команда перемещения 7 оси в -
05 Команда перемещения 8 оси в +
05 Команда перемещения 8 оси в -
06 Готовность УЧПУ
06 Активна G33
06 Блокировка обмена
06 Режим Автомат
06       Покадровый
06       Преднабор
06       Толчок
06       Выезд в ноль
07 Подтверждение приема координатной оси
07 Подтверждение выезда в ноль всех осей
07 Ускоренный ход
07 Программа выполняется
07 Тест без движения
07 Общий сброс "RESET"
07 Пропуск кадра
07 Останов по М01
08 Задание кадра
08 Блокировка выдачи MST-функций
08 Возврат на контур
08 Подача 0%
08 Активна G63  (подача 100%)
08 Активна G84
08 Активна G86
08 Разрешение сброса остатка пути
09 Строб М1
09 Строб М2
09 Строб М3
09 Строб Т1
09 Признак функции Т1
09 Строб Т2
09 Признак функции Т2
09            
10 Строб S1
10 Строб S1
10         
10         
10              
10       
10
10
11     
12 Значение
12 вcпомогательной
12 функции       
12 М1      
13 Значение
13 вcпомогательной
13 функции       
13 М1      
14 Значение
14 вcпомогательной
14 функции       
14 М2      
15 Значение
15 вcпомогательной
15 функции       
15 М2      
16 Значение
16 вcпомогательной
16 функции       
16 М3      
17 Значение
17 вcпомогательной
17 функции       
17 М3      
18 Т1 слово
19 Т1 слово
20 Т2 слово
21 Т2 слово
22 S1 слово
23 S1 слово
24 S1 слово
25 S1 слово
26 S2 слово
27 S2 слово
28 S2 слово
29 S2 слово
30 Код кнопки принят
30 Код аварийной кнопки принят
30
30
30
30
30
30
31 Подтверж-е вып-я перемещ-я с интерфейса
31 Выполнение перемещения с интерфейса
31
31 Строб заверш-я передачи адресов для инд-и
31 Признак адреса: 0-бит, 1-слово
31 Тип переменной:
31                 E-1, A-2, M-3,
31                 D-4, T-5, Z-6
32 Адрес переменной для индикации
33 Адрес переменной для индикации
34 Диапазон конечных выключателей
35 Диапазон конечных выключателей
36 DNC-сигналы
37 DNC-сигналы
38              
39 Контрольная сумма


