


	   /*  п/п программ круг.,винт. интерполяций */

      void cnccirds(void),
	   cnccict(void),
	   cnccireq(void),
	   cncciffi(INT ),
	   cnccirnc(void),
	   cncciinp(void),
	   cncciiol(INT,INT),
	   cncciout(void),
	   cnccilnc(REAL ,REAL ,REAL ,
		    REAL ,REAL ,REAL ,
		    REAL ,
		    REAL *,REAL *,REAL *,
		    REAL *),
	   cnccirrr(REAL ,REAL ),
	   cnccikcn(void),
	   cncciuna(void),
	   error(INT ),
	   cnccivnt(void),
	   cnccikrg(void);

//      void radius(),circuit(),kacan(),uniona(),error(),
//	 vint(),limit(),krug(),indp();

    /* п/п программ лин. инт.,обхода углов,зерк.,полярных коo.,пост.циклов*/


      void cnccilnr(void),
	   cnccilmn(REAL ,INT ),
	   cnccism0(void),
	   cnccimvp(INT ,INT ),
	   cncciclr(REAL *),
	   cnccieqv(REAL ),
	   cncciekl(INT ),
	   cncciabc(void),
	   cnccipol(void),
	   cnccirnd(void),
	   cnccicrs(REAL ,REAL ,REAL ,
		     REAL ,REAL ,REAL ,
		     REAL *,REAL *),
	   cnccifll(REAL,REAL),
	   cnccifdc(REAL,REAL,
		    REAL,REAL,REAL,REAL),
	   cnccicrc(REAL ,REAL ,REAL ,REAL ,
		     REAL ,REAL ,
		     REAL *,REAL *,
		     REAL *,REAL *),
	   cncciflr(INT,INT ,REAL ,REAL ),
	   cnccifdp(INT,INT),
	   cnccill(REAL ,REAL ,REAL ,
	     REAL ,REAL ,REAL ),
	   cnccifcl(void),
	   cnccifcc(REAL ,REAL ),
	   cncciicr(INT ,INT ),
	   cnccimrr1(void),
	   cncimrr2(void),
	    cnccidan(REAL ,REAL ,REAL ,REAL );
    void cnccilc(REAL ,REAL ,REAL ,REAL ,
	       REAL ,REAL ,REAL ,
		REAL *,REAL *,
		REAL *,REAL *),
	   cnccilr(INT ,INT ),
	   cnccisvl(void),
	   cnccidfi(void);
    REAL cnccialfa(REAL,REAL);
    INT cncciplc(INT,INT,REAL,REAL,REAL,REAL);

